/**
 * Temporary upload staging.
 *
 * Uploaded archives live in a private Supabase Storage bucket for exactly as
 * long as it takes the worker to pick them up. The object is deleted as soon as
 * it has been read — on the success path and on every failure path — and the
 * job row's `storage_key` is cleared by the same transaction that finishes the
 * job, so a finished job carrying a key is a detectable bug rather than a
 * silent leak.
 */
import { createWriteStream } from 'node:fs';
import { pipeline } from 'node:stream/promises';
import { Readable } from 'node:stream';
import { createClient } from '@supabase/supabase-js';
import type { SupabaseClient } from '@supabase/supabase-js';
import { IngestionError } from './errors.js';
import { log } from './logger.js';

export interface StorageOptions {
  url: string;
  serviceRoleKey: string;
  bucket: string;
}

export interface UploadStore {
  download(key: string, destination: string, maxBytes: number): Promise<number>;
  remove(key: string): Promise<void>;
}

/**
 * Storage keys are generated by the web app as `<userId>/<jobId>.zip`. They are
 * never user-supplied, but they are re-validated here because this module is
 * the thing that turns a string into a network path.
 */
const KEY_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.zip$/;

export function isValidStorageKey(key: string): boolean {
  return KEY_PATTERN.test(key);
}

export function createUploadStore(options: StorageOptions): UploadStore {
  const client: SupabaseClient = createClient(options.url, options.serviceRoleKey, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  return {
    async download(key, destination, maxBytes) {
      if (!isValidStorageKey(key)) {
        throw new IngestionError('storage_unavailable', 'storage key has an unexpected shape');
      }
      const { data, error } = await client.storage.from(options.bucket).download(key);
      if (error || !data) {
        throw new IngestionError('storage_unavailable', 'upload could not be downloaded', {
          cause: error,
        });
      }
      // `data` is a Blob. Size is checked before writing so an oversized object
      // never touches the disk, and again while streaming in case it lies.
      if (typeof data.size === 'number' && data.size > maxBytes) {
        throw new IngestionError('archive_too_large', 'staged upload exceeds the plan limit');
      }

      let received = 0;
      const file = createWriteStream(destination, { flags: 'wx', mode: 0o600 });
      const source = Readable.fromWeb(
        data.stream() as Parameters<typeof Readable.fromWeb>[0],
      );
      await pipeline(
        source,
        async function* (chunks: AsyncIterable<Buffer>) {
          for await (const chunk of chunks) {
            received += chunk.length;
            if (received > maxBytes) {
              throw new IngestionError('archive_too_large', 'staged upload exceeds the plan limit');
            }
            yield chunk;
          }
        },
        file,
      );
      return received;
    },

    async remove(key) {
      if (!isValidStorageKey(key)) return;
      const { error } = await client.storage.from(options.bucket).remove([key]);
      if (error) {
        // Deleting the staged upload is best-effort at this point: the job has
        // already finished one way or the other, and failing it now would be
        // worse. It is logged loudly because an accumulating bucket is a
        // retention problem.
        log.error('storage.delete_failed', { key: '<redacted>', reason: error.message });
      }
    },
  };
}
