import { RC_DISCLAIMER } from '../constants.js';
import type { Finding, ScanReport } from '../types.js';
import { formatHours, sourceLabel } from './text.js';

/**
 * Markdown checklist, sized for pasting into a GitHub issue or pull request.
 *
 * Never contains ANSI escapes. Findings are grouped into one checkbox per rule,
 * with locations beneath, so the checklist tracks decisions rather than lines.
 */

/** One checkbox per rule; the rule's title becomes the task. */
interface ChecklistGroup {
  ruleId: string;
  title: string;
  locations: string[];
}

export function renderChecklistReport(report: ScanReport): string {
  const out: string[] = [];
  const line = (text = ''): void => {
    out.push(text);
  };

  line(`## MCP ${report.target.protocolVersion} Migration Checklist`);
  line();
  line(
    `> ${RC_DISCLAIMER} Generated by \`mcp-upgrade\` v${report.scannerVersion} against ` +
      `\`${report.repository.root}\`.`,
  );
  line();
  line(
    `**Transport:** ${report.repository.transport} · ` +
      `**Readiness:** ${report.summary.readiness.score}/100 · ` +
      `**Estimated effort:** ${formatHours(report.summary.effort.minHours)}–` +
      `${formatHours(report.summary.effort.maxHours)} h`,
  );
  line();

  const errors = group(report.findings.filter((finding) => finding.level === 'error'));
  const reviews = group(report.findings.filter((finding) => finding.level === 'review'));
  const warnings = group(report.findings.filter((finding) => finding.level === 'warning'));
  const infos = group(report.findings.filter((finding) => finding.level === 'info'));

  if (errors.length === 0 && reviews.length === 0 && warnings.length === 0) {
    line('No blocking incompatibilities, deprecations or review items were detected.');
    line();
  }

  if (errors.length > 0) {
    line('### Confirmed incompatibilities');
    line();
    writeGroups(line, errors);
  }

  if (reviews.length > 0) {
    line('### Needs review');
    line();
    line('Static analysis could not decide these. Each needs a human judgement.');
    line();
    writeGroups(line, reviews);
  }

  if (warnings.length > 0) {
    line('### Deprecations');
    line();
    line(
      'These still work in ' +
        `${report.target.protocolVersion} and are not breaking changes. Plan the migration; ` +
        'the deprecation window is a minimum of twelve months.',
    );
    line();
    writeGroups(line, warnings);
  }

  if (infos.length > 0) {
    line('### Informational');
    line();
    line(`MCP Apps readiness: **${report.summary.appsReadiness}**.`);
    line();
    writeGroups(line, infos, /* checkboxes */ false);
  }

  line('### Effort breakdown');
  line();
  if (report.summary.effort.items.length === 0) {
    line('No migration work identified.');
  } else {
    for (const item of report.summary.effort.items) {
      line(`- ${item.label}: ${formatHours(item.minHours)}–${formatHours(item.maxHours)} h`);
    }
  }
  line();
  line(`Excludes ${report.summary.effort.excludes.join(', ')}.`);
  line();
  line('### References');
  line();
  for (const source of uniqueSources(report.findings)) {
    line(`- [${source.label}](${source.url})`);
  }

  return `${out.join('\n')}\n`;
}

function group(findings: Finding[]): ChecklistGroup[] {
  const groups = new Map<string, ChecklistGroup>();
  for (const finding of findings) {
    const existing = groups.get(finding.ruleId);
    const location = `\`${finding.file}:${finding.line}\``;
    if (existing) {
      if (!existing.locations.includes(location)) existing.locations.push(location);
      continue;
    }
    groups.set(finding.ruleId, {
      ruleId: finding.ruleId,
      title: finding.title,
      locations: [location],
    });
  }
  return [...groups.values()].sort((a, b) => a.ruleId.localeCompare(b.ruleId, 'en'));
}

function writeGroups(
  line: (text?: string) => void,
  groups: ChecklistGroup[],
  checkboxes = true,
): void {
  for (const entry of groups) {
    line(`${checkboxes ? '- [ ] ' : '- '}${entry.title} (\`${entry.ruleId}\`)`);
    // Keep the location list bounded so a checklist stays pasteable.
    const shown = entry.locations.slice(0, 10);
    for (const location of shown) line(`  - ${location}`);
    if (entry.locations.length > shown.length) {
      line(`  - …and ${entry.locations.length - shown.length} more location(s)`);
    }
  }
  line();
}

function uniqueSources(findings: Finding[]): { label: string; url: string }[] {
  const byUrl = new Map<string, { label: string; url: string }>();
  for (const finding of findings) {
    if (byUrl.has(finding.source.url)) continue;
    byUrl.set(finding.source.url, {
      label: sourceLabel(finding),
      url: finding.source.url,
    });
  }
  return [...byUrl.values()].sort((a, b) => a.label.localeCompare(b.label, 'en'));
}
