import { RC_DISCLAIMER } from '../constants.js';
import { compareCodeUnits } from '../order.js';
import type { Finding, ScanReport } from '../types.js';
import { formatHours, sourceLabel } from './text.js';

/**
 * Markdown checklist, sized for pasting into a GitHub issue or pull request.
 *
 * Never contains ANSI escapes. Findings are grouped into one checkbox per rule,
 * with locations beneath, so the checklist tracks decisions rather than lines.
 */

/** One checkbox per rule; the rule's title becomes the task. */
interface ChecklistGroup {
  ruleId: string;
  title: string;
  locations: string[];
}

export function renderChecklistReport(report: ScanReport): string {
  const out: string[] = [];
  const line = (text = ''): void => {
    out.push(text);
  };

  line(`## MCP ${report.target.protocolVersion} Migration Checklist`);
  line();
  line(
    `> ${RC_DISCLAIMER} Generated by \`mcp-upgrade\` v${report.scannerVersion} against ` +
      `${markdownCodeSpan(report.repository.root)}.`,
  );
  line();
  line(
    `**Transport:** ${report.repository.transport} · ` +
      `**Scan status:** ${report.scanStatus} · ` +
      `**Readiness:** ${report.summary.readiness.score}/100 · ` +
      `**Estimated effort:** ${formatHours(report.summary.effort.minHours)}–` +
      `${formatHours(report.summary.effort.maxHours)} h`,
  );
  line();

  if (report.scanStatus === 'partial') {
    line(
      '> **Partial scan:** One or more in-scope paths were not analyzed. Findings and the ' +
        'readiness estimate cover only the files that were scanned.',
    );
    line();
  }

  const errors = group(report.findings.filter((finding) => finding.level === 'error'));
  const reviews = group(report.findings.filter((finding) => finding.level === 'review'));
  const warnings = group(report.findings.filter((finding) => finding.level === 'warning'));
  const infos = group(report.findings.filter((finding) => finding.level === 'info'));

  if (errors.length === 0 && reviews.length === 0 && warnings.length === 0) {
    line(
      report.scanStatus === 'complete'
        ? 'No blocking incompatibilities, deprecations or review items were detected.'
        : 'No findings were detected in the files that were scanned. The scan is incomplete.',
    );
    line();
  }

  if (errors.length > 0) {
    line('### Confirmed incompatibilities');
    line();
    writeGroups(line, errors);
  }

  if (reviews.length > 0) {
    line('### Needs review');
    line();
    line('Static analysis could not decide these. Each needs a human judgement.');
    line();
    writeGroups(line, reviews);
  }

  if (warnings.length > 0) {
    line('### Warnings');
    line();
    line(
      'These are recommendation-level target behaviors or deprecated features. Read each ' +
        'finding and its official source before deciding whether a change is required.',
    );
    line();
    writeGroups(line, warnings);
  }

  if (infos.length > 0) {
    line('### Informational');
    line();
    line(`MCP Apps readiness: **${report.summary.appsReadiness}**.`);
    line();
    writeGroups(line, infos, /* checkboxes */ false);
  }

  if (report.issues.length > 0) {
    line('### Scan issues');
    line();
    const shown = report.issues.slice(0, 50);
    for (const issue of shown) {
      line(
        `- [ ] ${markdownCodeSpan(issue.code)} at ${markdownCodeSpan(issue.path)}: ` +
          markdownText(issue.message),
      );
    }
    if (report.issues.length > shown.length) {
      line(`- [ ] Review ${report.issues.length - shown.length} additional scan issue(s).`);
    }
    line();
  }

  line('### Effort breakdown');
  line();
  if (report.summary.effort.items.length === 0) {
    line('No migration work identified.');
  } else {
    for (const item of report.summary.effort.items) {
      line(
        `- ${markdownText(item.label)}: ${formatHours(item.minHours)}–` +
          `${formatHours(item.maxHours)} h`,
      );
    }
  }
  line();
  line(`Excludes ${report.summary.effort.excludes.map(markdownText).join(', ')}.`);
  line();
  line('### References');
  line();
  for (const source of uniqueSources(report.findings)) {
    line(`- [${markdownLinkText(source.label)}](${markdownLinkDestination(source.url)})`);
  }
  line();
  line(
    '> A clean report means that no implemented rule fired. It does not guarantee complete ' +
      'compatibility with the target MCP specification.',
  );

  return `${out.join('\n')}\n`;
}

function group(findings: Finding[]): ChecklistGroup[] {
  const groups = new Map<string, ChecklistGroup>();
  for (const finding of findings) {
    const existing = groups.get(finding.ruleId);
    const location = markdownCodeSpan(`${finding.file}:${finding.line}`);
    if (existing) {
      if (!existing.locations.includes(location)) existing.locations.push(location);
      continue;
    }
    groups.set(finding.ruleId, {
      ruleId: finding.ruleId,
      title: markdownText(finding.title),
      locations: [location],
    });
  }
  return [...groups.values()].sort((a, b) => compareCodeUnits(a.ruleId, b.ruleId));
}

function writeGroups(
  line: (text?: string) => void,
  groups: ChecklistGroup[],
  checkboxes = true,
): void {
  for (const entry of groups) {
    line(
      `${checkboxes ? '- [ ] ' : '- '}${entry.title} (${markdownCodeSpan(entry.ruleId)})`,
    );
    // Keep the location list bounded so a checklist stays pasteable.
    const shown = entry.locations.slice(0, 10);
    for (const location of shown) line(`  - ${location}`);
    if (entry.locations.length > shown.length) {
      line(`  - …and ${entry.locations.length - shown.length} more location(s)`);
    }
  }
  line();
}

function uniqueSources(findings: Finding[]): { label: string; url: string }[] {
  const byUrl = new Map<string, { label: string; url: string }>();
  for (const finding of findings) {
    if (byUrl.has(finding.source.url)) continue;
    byUrl.set(finding.source.url, {
      label: sourceLabel(finding),
      url: finding.source.url,
    });
  }
  return [...byUrl.values()].sort((a, b) => compareCodeUnits(a.label, b.label));
}

/** Removes characters that can create terminal controls or new Markdown blocks. */
function markdownText(value: string): string {
  let safe = '';
  for (const char of value) {
    const code = char.codePointAt(0) ?? 0;
    if (code === 0x09 || code === 0x0a || code === 0x0d) {
      safe += ' ';
      continue;
    }
    if (
      code < 0x20 ||
      (code >= 0x7f && code <= 0x9f) ||
      (code >= 0x202a && code <= 0x202e) ||
      (code >= 0x2066 && code <= 0x2069)
    ) {
      continue;
    }
    safe += char;
  }
  return safe.replace(/\s+/g, ' ').trim();
}

/** Uses a fence longer than any backtick run in the value. */
function markdownCodeSpan(value: string): string {
  const safe = markdownText(value);
  let longestRun = 0;
  for (const match of safe.matchAll(/`+/g)) longestRun = Math.max(longestRun, match[0].length);
  const fence = '`'.repeat(longestRun + 1);
  const needsPadding = /^[ `]|[ `]$/.test(safe);
  return `${fence}${needsPadding ? ' ' : ''}${safe}${needsPadding ? ' ' : ''}${fence}`;
}

function markdownLinkText(value: string): string {
  return markdownText(value).replace(/([\\[\]])/g, '\\$1');
}

function markdownLinkDestination(value: string): string {
  return markdownText(value)
    .replace(/%/g, '%25')
    .replace(/\\/g, '%5C')
    .replace(/\(/g, '%28')
    .replace(/\)/g, '%29')
    .replace(/</g, '%3C')
    .replace(/>/g, '%3E');
}
